### ISSUE TITLE
`activityColWrite` is never set for SubArray class

### ISSUE THREAD

**Issue by sepehrMSP** [neurosim/DNN_NeuroSim_V1.3#12]
Hi,
`activityColWrite` is variable that is used in many modules in the code. However, it is not set for SubArray class. Therefore its value is set to `0` by default and SubArray and its modules that use this variable will have wrong latency and power.
@neurosim 
@alu75

**Comment by neurosim** [comment]
Hi! In this version (inference engine focused), `activityColWrite` is not truly in use because writing/reprogramming is not necessary. The weights are assumed to be written into the memory arrays in advance, and only reading is required for the computation. While in DNN_NeuroSim_V2.1 (on-chip training focused), the `activityColWrite` is in use for weight reprogramming.
