### ISSUE TITLE
`readLatencyADC` and `CalculateclkFreq`

### ISSUE THREAD

**Issue by sepehrMSP** [neurosim/DNN_NeuroSim_V1.3#13]
Hi,
I have 3 questions:

1. why the `readLatencyADC` is just set to `numColMuxed`? I expect it to be initialized to something which its dimension is time like `X.readLatency`. However, I found `numColMuxed` just as the number of columns that share same read circuit that does not have any relation with time.
https://github.com/neurosim/DNN_NeuroSim_V1.3/blob/930c75772d43c733eb3090a5636761e058a16520/Inference_pytorch/NeuroSIM/SubArray.cpp#L853

2. In general, I cannot understand what is exactly the `CalculateclkFreq`. Can you give some description about it?
https://github.com/neurosim/DNN_NeuroSim_V1.3/blob/930c75772d43c733eb3090a5636761e058a16520/Inference_pytorch/NeuroSIM/SubArray.cpp#L848

3. In the above code snippet there is an `if` clause. In this cluase, `readLatency` is calculated by summing up latency of some modules like adc, switchmatrix and so on. The problem is that, unlike the previous `if` clause, the `CalculateLatency` method of the modules is not called. So it is expected that latency of the modules, i.e. `X.readLatency` is equal to zero which is wrong.

@neurosim 
@alu75

**Comment by neurosim** [comment]
Hi! We assume the chip frequency is limited by the analog sensing cycle, in other words, the critical path is from turning on WL/BLs to the currents summing along the columns and until the ADC converting them to digital numbers. `CalculateclkFreq` is used to get this critical path delay, i.e. clock period. After that, the circuit latency is counted as the number of cycles, then once reading requires 1 cycle. Because of column sharing, reading the whole array requires `numColMuxed` times. 
Hope this answers your question.

**Comment by sepehrMSP** [comment]
Hi, Thanks for your description about `CalculateclkFreq‍`. It's much clear now.
However still I could not get the answers of questions 1 and 3 yet.
@neurosim

**Comment by neurosim** [comment]
For your first question, as I mentioned in the last answer, after getting the clock period, the circuit latency is counted as the number of cycles. So the `readLatencyADC` is considered as 1 cycle per reading (though in fact ADC latency is less than 1 cycle and we actually count the latency of other peripheral modules like switch matrix and mux as ADC's. 1 cycle is the minimal unit now so we choose not to separate it). Because of column sharing, the latency of reading the whole array is `numColMuxed` cycles. 
For question 3, if you set the parameter `synchronous` as true, which means we will use the number of cycles to count the latency as I introduced before, then the code you mentioned won't use the `X.readLatency`. If the `synchronous` is false, which means not consider the clocks and directly accumulate the critical path delay of every module, then the `CalculateLatency` functions are called and the `X.readLatency` is in use. Paying attention to the `if` clauses about `CalculateclkFreq` and `synchronous` would help you understand the logic.

**Comment by neurosim** [comment]
Hi! The `shiftAdd.readLatency` can be the number of cycles or time depending on `param->synchronous`. Here the read latencies you listed all count the number of cycles. You can look at the codes in `ShiftAdd.cpp` for details.

**Comment by sepehrMSP** [comment]
Hi, another question about calculating latency :)
Consider the following piece of code:
```
if (!CalculateclkFreq) {
    if (numReadPulse > 1) {
        shiftAdd.CalculateLatency(numColMuxed);
    }
    if (param->synchronous) {
        readLatencyADC = numColMuxed;
    }
```
If `numColMuxed` = `numCol` = 128, then the ADC needs 128 cycles to read the bitline results.  However, based on the papers that I read (e.g. ISAAC), the ADC does all of the analog to digital conversions in a cycle. In fact, in many papers the frequency of ADC itself is mentioned, which also contributes to the power consumption, however I could not find this parameter in the `SarADC`.
Moreover, in the same example the `shiftAdd` needs at least 128 cycles. Now, in a pipline manner, I think it is not correct. Since at each cycle, the crossbar is activated and 128 results are provided. So I expect to do a MVM each cycle in the crossbar, however the `shiftAdd` alone needs 128 cycles that makes some conflicts.
@neurosim

**Comment by neurosim** [comment]
In the default setting, `numColMuxed` = 8 and `numCol` = 128. Because the area of ADC is large compared with memory cells, column sharing is commonly used. If 8 columns share one ADC (`numColMuxed` = 8), then it requires 8 cycles to read the whole crossbar. If you want to read once with all results, then you have to have more ADC.
In `SarADC`, we have the latency to compute the energy consumption.

**Comment by sepehrMSP** [comment]
> If 8 columns share one ADC (`numColMuxed` = 8), then it requires 8 cycles to read the whole crossbar.

I do not agree with this part. we can adjust the number of A2D conversions by increasing/decreasing the sampling rate of the ADC. So we are able to do the desire number of conversions in a 1 cycle concurrently. I want to assign 1 ADC to each subarray. In this case, the ADC have to be capable of doing 128 conversions in a cycle which needs to rise of sampling frequency of ADC (e.g 1.2 Gsample/second in ISAAC).
My problem is that why reading `n` columns needs `n` cycles?

**Comment by neurosim** [comment]
The 128 columns operate in parallel, then how could you convert them through 1 ADC? The problem is not the frequency of ADC, but the parallelization I think.
