### ISSUE TITLE
Issue in Leakage Power.

### ISSUE THREAD

**Issue by msabri1372** [neurosim/DNN_NeuroSim_V1.3#34]
Hi,
Thanks for providing your scripts for interested people.

I have a question about the Leakage Power reported by Neurosim. Because there are a lot of intermediate buffers to store the results of each layer, the Leakage Buffer does not seems convenient to me. I have looked at the Buffer.cpp script, and I think the energy consumption for each cell ( wlDecoder, precharger, sramWriteDriver, senseAmp) is missed and just buffer has been considered. 

Best Regards,

Mohammad sabri

**Comment by neurosim** [comment]
Hi! Thanks for your interest in our work. But I don't get your question, because the leakage power and the dynamic energy of buffer submodules (e.g., wlDecoder, precharger, sramWriteDriver, senseAmp) are all included in our simulation at around line 190-200 in Buffer.cpp script.
`readWholeDynamicEnergy += wlDecoder.readDynamicEnergy + precharger.readDynamicEnergy + sramWriteDriver.readDynamicEnergy;
writeWholeDynamicEnergy += wlDecoder.writeDynamicEnergy + precharger.writeDynamicEnergy + sramWriteDriver.writeDynamicEnergy;
leakage += wlDecoder.leakage + precharger.leakage + sramWriteDriver.leakage + senseAmp.leakage;`
